---
name: Alex
surname: Muhl-Richardson
position: 
pronouns: 
address: 
phone: (+44) 07926295611
www:
#profilepic: "./data/profile.jpg"
email: a.muhl.richardson@gmail.com
#twitter: alexmuhl_r
github: alexmuhl-r
linkedin: alex-muhl-richardson
#googlescholar: scholar.google.com/citations?user=YXa0igwAAAAJ
aboutme: I am a behavioural scientist and psychologist who uses data to solve real-world problems. I have interests in human performance optimisation, individual differences in behaviour and sustainable behaviour change. I have extensive experience leading and managing programs of research and experimentation, including developing data collection methodologies, working with large datasets, statistics and data analysis, and developing and communicating actionable insights.
#headcolor: 015985
date:
output:
  vitae::awesomecv:
    page_total: true
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = TRUE, message = TRUE)
library(vitae)
library(tibble)
library(magrittr)
library(here)
library(readr)
library(glue)
library(dplyr)

source(file = here("data","data.r"))
```
 
# Experience
```{r EXPERIENCE}
experience %>%
  detailed_entries(
    with = jobTitle,
    what = employer,
    why = detail,
    when = glue::glue("{startDate} - {endDate}",.na = ""),
    where = where
  )
```

# Education
```{r EDUCATION}

education %>% 
  detailed_entries(
    with = degree,
    what = inst,
    why = detail,
    when = glue::glue("{startYear} - {endYear}",.na = ""),
    where = where
  )

```
# Skills

```{r SKILLS}
skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
```

# Projects

```{r PROJECTS}
projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where,
    .protect = FALSE
  )
```

\urlstyle{same}

# Selected Publications

```{r PUBLICATIONS}
bibliography_entries(publications) %>%
  arrange(desc(issued),desc(author$family))
```
\vspace{3mm}

<!-- # Selected Presentations -->

<!-- ```{r PRESENTATIONS} -->
<!-- bibliography_entries(presentations) %>% -->
<!--   arrange(desc(issued),desc(author$family)) -->
<!-- ``` -->